"""upload order

Revision ID: 15af785f5752
Revises: e5455a885c2b
Create Date: 2024-09-08 15:54:05.713579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15af785f5752'
down_revision: Union[str, None] = 'e5455a885c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_upload_order_key', 'tasks', type_='unique')
    op.drop_column('tasks', 'upload_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('upload_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('tasks_upload_order_key', 'tasks', ['upload_order'])
    # ### end Alembic commands ###
