"""Updated task model

Revision ID: f4ddabd201e3
Revises: 
Create Date: 2024-10-05 16:18:08.020717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ddabd201e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('translated_text', sa.String(), nullable=True))
    op.drop_column('tasks', 'output_file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('output_file_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'translated_text')
    # ### end Alembic commands ###
